### ISSUE TITLE
Open epub error 

### ISSUE THREAD

**Issue by sirius-fan** [geek1011/BookBrowser#78]
I can not read epub on chromium，but firefox can
chromium version 72.0.3626.121（stable）Manjaro Linux （64 bit）

![image](https://user-images.githubusercontent.com/25720015/54188893-a5224280-44eb-11e9-80ff-e7038f304dc9.png)
Error message:
> Uncaught TypeError: Cannot read property 'pageFromCfi' of undefined

> {"error":"TypeError: Cannot read property 'pageFromCfi' of undefined","stack":"TypeError: Cannot read property 'pageFromCfi' of undefined\n at Rendition.located (http://localhost:8090/static/reader/epub/libs/epub.js:7296:39)\n at Rendition.reportedLocationAfterRAF (http://localhost:8090/static/reader/epub/libs/epub.js:7189:26)\n at d (https://cdn.ravenjs.com/3.26.2/raven.min.js:2:4702)","msg":"Uncaught TypeError: Cannot read property 'pageFromCfi' of undefined","url":"https://cdn.ravenjs.com/3.26.2/raven.min.js","line":2,"column":4725}

**Comment by pgaskin** [comment]
I would need to see the original epub file. Can you send it to me (you can email me)?
