### ISSUE TITLE
bug when rendering certain books

### ISSUE THREAD

**Issue by obbardc** [geek1011/BookBrowser#94]
I am running the master branch of BookBrowser, but get an error when reading some epub file. The file renders fine using https://pgaskin.net/ePubViewer/

The error message when clicking on the book is:-

```
error loading cover: TypeError: Cannot read property 'substr' of undefined

{"error":"TypeError: Cannot read property 'substr' of undefined","stack":"TypeError: Cannot read property 'substr' of undefined\n at Archive.getBlob (http://127.0.0.1:8090/static/reader/epub/libs/epub.js:16017:53)\n at Archive.createUrl (http://127.0.0.1:8090/static/reader/epub/libs/epub.js:16102:21)\n at App.onBookCoverLoaded (http://127.0.0.1:8090/static/reader/epub/script.js:326:29)"}
```

**Comment by obbardc** [comment]
Ah, it seems like ePubViewer in BookBrowser/master is v3.0.0 but ePubViewer on your site is v3.1.0

**Comment by geek1011** [comment]
I'll update ePubViewer soon. The issue seems to be on books without covers.
